name: Pull Request Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  job_test:
    name: Testando código
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2

      - run: yarn install
      - run: yarn test